###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Edgar Vallejo Curti",
    "email": "is72576@iteso.mx",
    "password": "password",
    "foo": "bar"
}

###
POST https://daws-eshop.herokuapp.com/api/users
Content-Type: application/json

{
    "name": "test",
    "email": "test",
    "password": "test"
}

###

POST https://daws-eshop.herokuapp.com/api/login
Content-Type: application/json

{
    "email": "is725762@iteso.mx",
    "password": "password"
}

###

GET http://localhost:3000/api/articles/4cBeLPzUC
Content-Type: application/json

###
GET http://localhost:3000/api/users/is725762@iteso.mx
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ

###

GET http://localhost:3000/api/articles
Content-Type: application/json

###
POST http://localhost:3000/api/articles
Content-Type: application/json
X-Admin: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJFVkMiOiJpczcyNTc2MiIsIkVOViI6ImlzNzE1MTU1In0.Y9A6bo3Nesum5EslwIC4ib8STGRVQpMB_6qA2llXc4o

{
    "inStock": 666,
    "price": 1999,
    "description": "test",
    "image": ""
}

###

GET http://localhost:3000/api/cart/GDZYq8es8
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ

###

PUT http://localhost:3000/api/cart/GDZYq8es8
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ 

{
  "content": {
      "4cBeLPzUC": 1,
      "GWAl1ZlYs": 2
  }
}

###

GET http://localhost:3000/api/bills/GDZYq8es8
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ 

###
POST http://localhost:3000/api/bills/GDZYq8es8
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ 

{
    "state": "JAL",
    "city": "Zapopan",
    "direction": "Paseo de las caobas",
    "cp": 45188,
    "internNumber": "104",
    "externNumber": "3320"
}

###

PUT http://localhost:3000/api/articles/9ZRfyG5LS
Content-Type: application/json
X-Admin: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJFVkMiOiJpczcyNTc2MiIsIkVOViI6ImlzNzE1MTU1In0.Y9A6bo3Nesum5EslwIC4ib8STGRVQpMB_6qA2llXc4o

{
    "inStock": 69,
    "price": 30,
    "description": "Test put article"
}

