###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Edgar Vallejo Curti",
    "email": "is725762@iteso.mx",
    "password": "password"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "is725762@iteso.mx",
    "password": "password"
}

###

GET http://localhost:3000/api/users/is725762@iteso.mx
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ

###

GET http://localhost:3000/api/articles
Content-Type: application/json

###
POST http://localhost:3000/api/articles
Content-Type: application/json
X-Admin: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJFVkMiOiJpczcyNTc2MiIsIkVOViI6ImlzNzE1MTU1In0.Y9A6bo3Nesum5EslwIC4ib8STGRVQpMB_6qA2llXc4o

{
    "inStock": 666,
    "price": 1999,
    "description": "Adidas Forum Low",
    "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/09c5ea6df1bd4be6baaaac5e003e7047_9366/Tenis_Forum_Low_Blanco_FY7756_01_standard.jpg"
}

###

GET http://localhost:3000/api/cart/GDZYq8es8
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ

###

PUT http://localhost:3000/api/cart/GDZYq8es8
Content-Type: application/json
X-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjExMjY3NzIsImV4cCI6MTYyMTIxMzE3Mn0.Ww0olsOoajC93dpZ_u7NqslK7aA10Px3wVkxeBuWwIQ 

{
  "content": {
      "4cBeLPzUC": 1
  }
}